version: '2.4'
volumes:
  node_modules: ~
  public: ~
  mysqldb_data: ~

services:
  nginx:
    image: nginx
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - public:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      php:
        condition: service_started
      node:
        condition: service_started

  node:
    image: node:16
    working_dir: /node
    entrypoint: make
    command: node-assets
    ports:
      - "8080:8080"
    volumes:
      - node_modules:/node/node_modules
      - public:/node/public
      - ./Makefile:/node/Makefile
      - ./artisan:/node/artisan
      - ./resources:/node/resources
      - ./package.json:/node/package.json
      - ./package-lock.json:/node/package-lock.json
      - ./tailwind.config.js:/node/tailwind.config.js
      - ./webpack.mix.js:/node/webpack.mix.js
      - ./webpack.config.js:/node/webpack.config.js
  php:
    build:
      context: .
      target: dev
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
      interval: 1s
    volumes:
      - mysqldb_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
